---
title: "Analysis"
author: "Mikhail Dozmorov"
date: "`r Sys.Date()`"
output:
  pdf_document:
    toc: no
  html_document:
    theme: cerulean
    toc: yes
---

```{r setup, echo=FALSE, message=FALSE, warning=FALSE}
# Set up the environment
library(knitr)
opts_chunk$set(cache.path='cache/', fig.path='img/', cache=F, tidy=T, fig.keep='high', echo=F, dpi=100, warnings=F, message=F, comment=NA, warning=F, results='as.is', fig.width = 10, fig.height = 6) #out.width=700, 
library(pander)
panderOptions('table.split.table', Inf)
set.seed(1)
library(dplyr)
options(stringsAsFactors = FALSE)
```

```{r libraries}
library(ggplot2)
library(cowplot)
library(readxl)
library("ggsci")
# scales::show_col(pal_lancet("lanonc")(8))
mycols = pal_lancet("lanonc")(8)
```

```{r settings}
p_adj_cutoff <- -log10(1e-5)

data_dir       <- "/Users/mdozmorov/Documents/Work/VCU_work/misc/Sarah_Spiegel/2020-08.Green/" # Working directory
fileNameIn <- file.path(data_dir, "results/DEGs_enrichR3.1.xlsx")
# Number of features to plot, for UP and DN
n_features <- 10
# Mutually exclusive selectors, which analysis should be run. Only one may be TRUE
human_analysis <- FALSE
mouse_analysis <- TRUE

if (human_analysis) {
  KEGG <- "KEGG_2019_Human"
  WikiPathways <- "WikiPathways_2019_Human"
}
if (mouse_analysis) {
  KEGG <- "KEGG_2019_Mouse"
  WikiPathways <- "WikiPathways_2019_Mouse"
}
```

```{r}
plot_panel <- function(sheet = KEGG) {
  mtx <- read_xlsx(fileNameIn, sheet = sheet)
  # Separate up and down enrichments
  mtx_up <- mtx[mtx$Direction == "UP", ]
  mtx_dn <- mtx[mtx$Direction == "DN", ]
  if (nrow(mtx_up) == 0 ) {
    mtx <- mtx_dn[1:min(n_features, nrow(mtx_dn)), ]
  } else if (nrow(mtx_dn) == 0) {
    mtx_up[1:min(n_features, nrow(mtx_up)), ]
  } else {
    # Take top X
    mtx <- rbind(mtx_up[1:min(n_features, nrow(mtx_up)), ],
                 mtx_dn[1:min(n_features, nrow(mtx_dn)), ])
  }
  
  
  
  
  mtx_to_plot <- data.frame("Feature" = mtx$Term,
                            "Pvalue"  = -1 * log10(mtx$Adjusted.P.value),
                            "Group"   = mtx$Direction)
  
  mtx_to_plot$Pvalue[mtx_to_plot$Group == "DN"] <- -1 * mtx_to_plot$Pvalue[mtx_to_plot$Group == "DN"]
  # mtx_to_plot <- mtx_to_plot[order(mtx_to_plot$Pvalue, decreasing = TRUE), ]
  
  mtx_to_plot$Feature <- factor(mtx_to_plot$Feature, levels = rev(mtx_to_plot$Feature))
  
  ggplot(mtx_to_plot, aes(x = Feature, y = Pvalue, fill = Group)) +
    geom_bar(stat = "identity") +
    scale_fill_manual(values = mycols[c(1, 2)]) +
    theme_bw() +
    coord_flip() +
    ylab("-log10(p-value)") +
    scale_y_continuous(breaks = seq(-80, 310, 20))
  
  fileNameOut <- file.path(data_dir, paste0("results/Figure_", sheet, ".jpg"))
  ggsave(filename = fileNameOut, height = 3, width = 8)
}
```

```{r}
for (sheet in c(KEGG, "GO_Biological_Process_2018", "GO_Molecular_Function_2018", "Panther_2016", "TRANSFAC_and_JASPAR_PWMs")) {
  plot_panel(sheet)
}
```

