---
title: "oncoEnrichR Analysis"
author: "Mikhail Dozmorov"
date: "`r Sys.Date()`"
output:
  pdf_document:
    toc: no
  html_document:
    theme: cerulean
    toc: yes
---

```{r setup, echo=FALSE, message=FALSE, warning=FALSE}
# Set up the environment
library(knitr)
opts_chunk$set(cache.path='cache/', fig.path='img/', cache=F, tidy=T, fig.keep='high', echo=F, dpi=100, warnings=F, message=F, comment=NA, warning=F, results='as.is', fig.width = 10, fig.height = 6) #out.width=700, 
library(pander)
panderOptions('table.split.table', Inf)
set.seed(1)
library(dplyr)
options(stringsAsFactors = FALSE)
```

See https://github.com/sigven/oncoEnrichR for an overview of the functionality

# Libraries

```{r libraries}
# BiocManager::install(c("TissueEnrich", "assertable", "textclean"))
# BiocManager::install('sigven/oncoEnrichR', update = FALSE)
library(oncoEnrichR)
library(readxl)
library(writexl)
library(ggplot2)
library(ggridges)
```

# Load data

```{r data}
# Input settings
dir_data <- "/Users/mdozmorov/Documents/Data/GoogleDrive/HiC_files/results/RNA-seq/2021.11.19_UCD52_DEG"
fileNameIn <- file.path(dir_data, "results/04.06.22_DEGs_edgeR_UCD52PR_CR_annotated.xlsx")
sheet_name <- "DEGs"
# oncoEnrichR settings, depending on input gene IDs
query_id_type = "ensembl_gene"
# Output settings
analysis_name <- "04.06.22_DEGs"
fileNameOutUP1  <- file.path(dir_data, "results", paste0("oncoEnrichR_", analysis_name, "_UP.html"))
fileNameOutUP2  <- file.path(dir_data, "results", paste0("oncoEnrichR_", analysis_name, "._UP.xlsx"))
fileNameOutDN1  <- file.path(dir_data, "results", paste0("oncoEnrichR_", analysis_name, "_DN.html"))
fileNameOutDN2  <- file.path(dir_data, "results", paste0("oncoEnrichR_", analysis_name, "._DN.xlsx"))
# Create "results" folder, if does not exist
if (!dir.exists(file.path(dir_data, "results"))) dir.create(file.path(dir_data, "results"))
# Create "results" folder, if does not exist
if (!dir.exists(file.path(dir_data, "oeDBcache"))) dir.create(file.path(dir_data, "oeDBcache"))
```

# Load data

```{r}
# Read the data
mtx <- read_xlsx(fileNameIn, sheet = sheet_name)
# Create a data frame for downstream processing - adjust column names
mtx <- data.frame(Gene = mtx$ensgenes,
                  UPDN = ifelse(mtx$logFC > 0, "Upregulated", "Downregulated"),
                  FDR  = mtx$FDR)
# Sort by FDR
mtx <- mtx[order(mtx$FDR), ]
# Exploratory data analysis
print("Number of up- and downregulated genes")
ggplot(mtx, aes(y = UPDN)) + geom_bar()

print("Summary of the adjusted p-value")
summary(mtx$FDR)

print("Adjusted p-value discribution separately for up- and downregulated genes")
ggplot(mtx, aes(x = FDR, y = UPDN)) + geom_density_ridges()

# Set Cutoffs
p_adj_cutoff_gene <- 0.05
max_genes <- 2500 # Maximum number of genes to run enrichment analysis on

# Filter the data and make query gene lists
mtx <- mtx[mtx$FDR < p_adj_cutoff_gene, ]
query_UP <- mtx$Gene[mtx$UPDN == "Upregulated"]
query_DN <- mtx$Gene[mtx$UPDN == "Downregulated"]
# Filter if gene lists are too long (or short)
query_UP <- query_UP[1:min(max_genes, length(query_UP))]
query_DN <- query_DN[1:min(max_genes, length(query_DN))]
```

# Analysis

```{r}
# See https://github.com/sigven/oncoEnrichR
oncoEnrichR_wrapper <- function(query = query_UP, oeDB = oeDB,
                                query_id_type = query_id_type, 
                                project_title = analysis_name) {
  onco_enrich(
    query,
    oeDB,
    query_id_type = query_id_type,
    ignore_id_err = TRUE,
    project_title = project_title,
    project_owner = "Mikhail Dozmorov",
    project_description = project_title,
    bgset = NULL,
    bgset_id_type = "symbol",
    bgset_description = "All protein-coding genes",
    p_value_cutoff_enrichment = 0.05,
    p_value_adjustment_method = "BH",
    q_value_cutoff_enrichment = 0.2,
    min_geneset_size = 10,
    max_geneset_size = 500,
    min_subcellcomp_confidence = 1,
    subcellcomp_show_cytosol = FALSE,
    simplify_go = TRUE,
    ppi_add_nodes = 50,
    ppi_score_threshold = 900,
    show_ppi = TRUE,
    show_drugs_in_ppi = TRUE,
    show_disease = TRUE,
    show_top_diseases_only = TRUE,
    show_cancer_hallmarks = TRUE,
    show_drug = TRUE,
    show_enrichment = TRUE,
    show_tcga_aberration = TRUE,
    show_tcga_coexpression = TRUE,
    show_subcell_comp = TRUE,
    show_crispr_lof = TRUE,
    show_cell_tissue = FALSE,
    show_prognostic_cancer_assoc = TRUE,
    show_complex = TRUE)
}

oeDB <- oncoEnrichR::load_db(cache_dir = file.path(dir_data, "oeDBcache"))
```

```{r}
# Analysis of upregulated genes
report_UP <- oncoEnrichR_wrapper(query = query_UP, oeDB = oeDB, query_id_type = query_id_type, project_title = analysis_name)
oncoEnrichR::write(report = report_UP, file = fileNameOutUP1, format = "html", overwrite = TRUE)
oncoEnrichR::write(report = report_UP, file = fileNameOutUP2, format = "excel", overwrite = TRUE)
# Analysis of upregulated genes
report_DN <- oncoEnrichR_wrapper(query = query_DN, oeDB = oeDB, query_id_type = query_id_type, project_title = analysis_name)
oncoEnrichR::write(report = report_DN, file = fileNameOutDN1, format = "html", overwrite = TRUE)
oncoEnrichR::write(report = report_DN, file = fileNameOutDN2, format = "excel", overwrite = TRUE)

print("Done. Results are in")
print(fileNameOutUP1)
print(fileNameOutUP2)
print(fileNameOutDN1)
print(fileNameOutDN2)
```

